apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vklim4ntovich
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Vitali Project
  sourceRepos:
    - https://github.com/klimantovich/GymManagementSystem

  destinations:
    - server: https://kubernetes.default.svc
      name: in-cluster
      namespace: "gymmanagement"

  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    - group: "*"
      kind: Namespace

  # Deny all namespaced-scoped resources from being created, except for Deployment and StatefulSet
  namespaceResourceWhitelist:
    - group: "apps"
      kind: Deployment
    - group: "*"
      kind: ConfigMap
    - group: "*"
      kind: Secret
    - group: "networking.k8s.io"
      kind: Ingress
    - group: "*"
      kind: Service
