{{- if .Values.ingress.enabled -}}
{{- $svcPort := .Values.service.port -}}
{{- $svcName := include "gymmanagement.serviceName" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gymmanagement.fullname" . }}-ingress
  labels:
    {{- include "gymmanagement.labels" . | nindent 4 }}
  {{- if or .Values.ingress.httpAuth.enabled .Values.ingress.annotations }}
  annotations:
    {{- with .Values.ingress.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.httpAuth.enabled }}
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: {{ include "gymmanagement.authSecretName" . }}
    nginx.ingress.kubernetes.io/auth-realm: "{{ .Values.ingress.httpAuth.realmString }}"
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - pathType: {{ .pathType }}
            path: {{ .path }}
            backend:
              service:
                name: {{ $svcName }}
                port:
                  number: {{ $svcPort }}
        {{- end }}
    {{- end }}
{{- end }}
