apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gymmanagement.secretName" . }}
type: Opaque
data:
  db_password: "{{ .Values.secret.db_password | b64enc }}"

---
{{- if .Values.ingress.httpAuth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gymmanagement.authSecretName" . }}
type: Opaque
data:
  auth: {{ (htpasswd .Values.ingress.httpAuth.user .Values.ingress.httpAuth.password) | b64enc }}
{{- end -}}